---
- name: Test deployment 
  hosts: web
  become: no
  gather_facts: yes
  
  tasks:
    - name: Echo success message
      debug:
        msg: "This is a test deployment on {{ inventory_hostname }}"

    - name: Display ansible version
      debug:
        msg: "Ansible version: {{ ansible_version.full }}"

    - name: Create a test file
      file:
        path: /tmp/ansible_test.txt
        state: touch
        mode: '0644'

    - name: Write to test file
      copy:
        content: "Deployment test successful on {{ ansible_date_time.date }} at {{ ansible_date_time.time }}"
        dest: /tmp/ansible_test.txt

    - name: Show content of test file
      command: cat /tmp/ansible_test.txt
      register: file_content
      changed_when: false

    - name: Display file content
      debug:
        var: file_content.stdout_lines 